services:
  redis:
    image: redis:7-alpine
    container_name: bot_farm_redis
    restart: always
    volumes:
      - ./data/redis:/data

  ai_assistant:
    build: .
    container_name: ai_assistant_bot
    restart: always
    env_file: .env
    command: python bots/ai_assistant/main.py
    depends_on:
      - redis

  welcome_bot:
    build: .
    container_name: welcome_bot
    restart: always
    env_file: .env
    command: python bots/welcome_bot/main.py
    depends_on:
      - redis

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "0.0.0.0:8001:8001" # Explicitly bind to all network interfaces
    depends_on:
      - redis